import {describe,it,expect} from 'vitest';
import {evaluateAmount,isAmountFormula} from './amount';
import {blankBook,parseAmount,editMonth,validateTransaction,calc} from './model';
import {csv,importCSV} from './export';
describe('simple amount formulas',()=>{
 it('converts biweekly amounts to monthly and calculates shared expenses',()=>{expect(evaluateAmount('65*26/12')).toBe(14083);expect(evaluateAmount('120-45')).toBe(7500);expect(evaluateAmount('(80+20)/2')).toBe(5000);expect(evaluateAmount('=65 × 26 ÷ 12')).toBe(14083);});
 it('respects operator precedence, whitespace, parentheses and unary signs',()=>{expect(evaluateAmount(' 2 + 3 * 4 ')).toBe(1400);expect(evaluateAmount('-(2 + 3)*4')).toBe(-2000);expect(evaluateAmount('20 / 2 / 2')).toBe(500);expect(evaluateAmount('10 - -2')).toBe(1200);expect(evaluateAmount('.5 + 1.')).toBe(150);expect(evaluateAmount('−30+10')).toBe(-2000);});
 it('uses exact decimal arithmetic and rounds only the final result to cents',()=>{expect(evaluateAmount('0.1+0.2')).toBe(30);expect(evaluateAmount('1.005')).toBe(101);expect(evaluateAmount('-1.005')).toBe(-101);expect(evaluateAmount('0.005+0.005')).toBe(1);expect(evaluateAmount('1/3*3')).toBe(100);expect(evaluateAmount('10/6')).toBe(167);expect(evaluateAmount('-0.004')).toBe(0);});
 it('preserves nullable blank actuals, ordinary numeric amounts and the amount limit',()=>{expect(evaluateAmount(' ',true)).toBeNull();expect(evaluateAmount('0')).toBe(0);expect(evaluateAmount('-272.59')).toBe(-27259);expect(evaluateAmount('10000000000')).toBe(1e12);expect(()=>evaluateAmount('10000000000+0.01')).toThrow('amount');});
 it('rejects unfinished expressions, division by zero, scripts and unsupported syntax',()=>{for(const s of ['', '=', '12+', '(1+2', '1+2)', '1 2', '1/0', '1/(2-2)', 'Math.random()', 'alert(1)', '1e3','2**3','1;2','1,000','20%','2(3)','2//3'])expect(()=>evaluateAmount(s),s).toThrow('amount');});
 it('bounds input length and nesting',()=>{expect(()=>evaluateAmount('1'.repeat(257))).toThrow('amount');expect(()=>evaluateAmount('('.repeat(33)+'1'+')'.repeat(33))).toThrow('amount');});
 it('stores numeric cents for plans, actuals, assets, openings and transactions; CSV stays compatible',()=>{let b=blankBook();b=editMonth(b,'2026-10',m=>{m.plan.investment=parseAmount('65*26/12')!;m.actual.mv=parseAmount('2000+650');m.assets.dca=parseAmount('100+50/2');m.transactions.push({id:'formula-test',date:'2026-10-04',item:'Split payment',category:'Groceries',amount:parseAmount('120-45')!,fund:''});});b.opening.funds.General=parseAmount('-300+27.41')!;validateTransaction(b.months['2026-10'].transactions[0],'2026-10');expect(calc(b,'2026-10').savings).toBe(65000);expect(b.months['2026-10'].plan.investment).toBe(14083);expect(importCSV(csv(b))).toEqual(b);});
 it('detects formulas without treating an ordinary negative amount as one',()=>{expect(isAmountFormula('-1.23')).toBe(false);expect(isAmountFormula('120-45')).toBe(true);expect(isAmountFormula('=65*26/12')).toBe(true);});
});
