import {useEffect,useRef,useState,type ReactNode,type FormEvent} from 'react';
import {AnimatePresence,motion,MotionConfig,useDragControls,useMotionValue,animate} from 'motion/react';
import {House,List,Layers,CheckCheck,Plus,Settings,ChevronDown,ChevronRight,X,ArrowUpRight,Search,Plane,PawPrint,Shield,Wallet,Download,Check,ArrowDownLeft} from 'lucide-react';
import {useRegisterSW} from 'virtual:pwa-register/react';
import {MONTHS,FUNDS,GROUPS,KEYS,LABELS,DAILY,CATEGORIES,blankBook,calc,position,money,actual,shortMonth,monthLabel,cents,dollars,editMonth,closeMonth,reopenMonth,validateBook,todayIn,validateTransaction,type Book,type MonthId,type Month,type Transaction,type Fund,type Category} from './model';
import {loadBook,saveBook} from './storage';
import {archive,download} from './export';
const pages=['本月','记账','资金','月结'],icons=[House,List,Layers,CheckCheck],fundIcons=[Shield,Plane,PawPrint,Wallet];
function Sheet({title,close,children}:{title:string,close:()=>void,children:ReactNode}){const ref=useRef<HTMLDialogElement>(null),drag=useDragControls();useEffect(()=>{ref.current?.showModal();const before=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=before;};},[]);return <dialog ref={ref} onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===ref.current)close();}}><motion.section className="sheet" initial={{y:'100%'}} animate={{y:0}} exit={{y:'100%'}} transition={{type:'spring',stiffness:380,damping:36}} drag="y" dragControls={drag} dragListener={false} dragConstraints={{top:0,bottom:0}} dragElastic={{top:0,bottom:.5}} onDragEnd={(_,info)=>{if(info.offset.y>110||info.velocity.y>550)close();}}><div className="handle" onPointerDown={e=>drag.start(e)}><i/></div><header><h2>{title}</h2><button className="round" onClick={close} aria-label="关闭"><X size={20}/></button></header><div className="sheet-body">{children}</div></motion.section></dialog>;}
function AmountInput({label,value,onChange,blank=false}:{label:string,value:number|null,onChange:(v:number|null)=>void,blank?:boolean}){return <label className="field"><span>{label}</span><input key={label+String(value)} aria-label={label} inputMode="decimal" type="text" defaultValue={value===null?'':dollars(value).toFixed(2)} placeholder={blank?'未确认':'0.00'} onBlur={e=>{const s=e.target.value.trim();if(s===''&&blank){onChange(null);return;}if(!/^-?\d+(\.\d{0,2})?$/.test(s)){e.target.setCustomValidity('请输入最多两位小数的金额');e.target.reportValidity();return;}e.target.setCustomValidity('');onChange(cents(Number(s)));}}/></label>;}
export default function App(){
 const [book,setBook]=useState<Book|null>(null),[loading,setLoading]=useState(true),[page,setPage]=useState(0),[id,setId]=useState<MonthId>('2026-10'),[panel,setPanel]=useState<string|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[editing,setEditing]=useState<Transaction|null>(null),[undo,setUndo]=useState<{id:MonthId,t:Transaction}|null>(null),[preview,setPreview]=useState<Book|null>(null);
 const [preparedArchive,setPreparedArchive]=useState<{url:string,name:string}|null>(null);useEffect(()=>()=>{if(preparedArchive)URL.revokeObjectURL(preparedArchive.url);},[preparedArchive]);
 const latest=useRef<Book|null>(null),queue=useRef(Promise.resolve()),file=useRef<HTMLInputElement>(null);
 const {needRefresh:[update],updateServiceWorker}=useRegisterSW();
 useEffect(()=>{loadBook().then(b=>{latest.current=b;setBook(b);}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 const commit=(b:Book)=>{validateBook(b);latest.current=b;setBook(b);queue.current=queue.current.catch(()=>{}).then(()=>saveBook(b)).catch(e=>setError(e.message));};
 const attempt=(f:()=>void)=>{try{setError('');f();}catch(e){setError((e as Error).message);}};
 const change=(f:(m:Month)=>void)=>{if(latest.current)commit(editMonth(latest.current,id,f));};
 const modify=(f:(b:Book)=>void)=>{if(latest.current){const b=structuredClone(latest.current);f(b);commit(b);}};
 useEffect(()=>{const s=book?.settings;document.documentElement.dataset.theme=s?.theme||'system';document.documentElement.dataset.opaque=String(s?.reduceTransparency||false);document.documentElement.style.setProperty('--glass-alpha',String(.34+(s?.glass??65)*.005));},[book?.settings]);
 useEffect(()=>{const vv=window.visualViewport;const resize=()=>document.documentElement.style.setProperty('--keyboard',`${Math.max(0,window.innerHeight-(vv?.height??window.innerHeight)-(vv?.offsetTop??0))}px`);vv?.addEventListener('resize',resize);return()=>vv?.removeEventListener('resize',resize);},[]);
 const restore=async(f:File)=>{try{if(f.size>20000000)throw new Error('文件过大。');setPreview(validateBook(JSON.parse(await f.text())));setPanel('restore');}catch(e){setError((e as Error).message);}};
 const doExport=async()=>{if(!latest.current)return;setBusy(true);try{let b=latest.current;if(!b.months[id].closed)b=closeMonth(b,id);await saveBook(b);commit(b);const data=await archive(b,id);const archiveName=`VEWU-${id}-v${b.months[id].revision}.zip`;setPreparedArchive({url:URL.createObjectURL(data),name:archiveName});download(data,archiveName);modify(x=>{x.months[id].exportedRevision=x.months[id].revision;x.months[id].exportedAt=new Date().toISOString();});setNotice('归档包已生成，请在“文件”中确认下载。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const inputFile=<input ref={file} type="file" accept=".json,application/json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void restore(f);e.target.value='';}}/>;
 if(loading)return <main className="welcome"><p>正在打开本地账本…</p></main>;
 if(!book)return <><main className="welcome"><div className="brand-mark">V</div><span className="eyebrow">VEWU FINANCE</span><h1>生活有度。<br/>余裕有数。</h1><p>从一个清晰的月份开始。<br/>账本保存在这台设备，随时备份与导出。</p><button className="primary" onClick={()=>file.current?.click()}>导入私人账本</button><button className="plain" onClick={()=>commit(blankBook())}>创建空白账本</button><small>OCT — DEC 2026 · LOCAL FIRST</small>{error&&<p role="alert">{error}</p>}</main>{inputFile}{panel==='restore'&&preview&&<Sheet title="导入账本" close={()=>setPanel(null)}><p>载入 Oct–Dec 2026，共 {MONTHS.reduce((n,m)=>n+preview.months[m].transactions.length,0)} 笔交易。</p><button className="primary" onClick={()=>{commit(preview);setPreview(null);setPanel(null);}}>确认导入</button></Sheet>}</>;
 const m=book.months[id],c=calc(book,id),p=position(book,id),unconfirmed=KEYS.filter(k=>!DAILY[k]&&m.actual[k]===null).length;
 const transactions=m.transactions.filter(t=>(filter==='all'||filter==='ordinary'&&!t.fund||t.fund===filter)&&`${t.item} ${t.category} ${t.fund}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date));
 const openTx=(t:Transaction|null=null)=>{setEditing(t);setPanel('transaction');};
 const row=(label:string,value:string,sub?:string,action?:()=>void)=><button className="row" onClick={action} disabled={!action}><span>{label}{sub&&<small>{sub}</small>}</span><strong>{value}</strong>{action&&<ChevronRight size={16}/>}</button>;
 return <MotionConfig reducedMotion={book.settings.reduceMotion?'always':'user'}><div className="app"><header className="topbar"><span className="wordmark">VEWU<span> FINANCE</span></span><button className="round glass" aria-label="设置" onClick={()=>setPanel('settings')}><Settings size={21}/></button></header><main><div className="title-line"><div><span className="eyebrow">2026 · QUARTER FOUR</span><h1>{page===0?shortMonth(id):pages[page]}</h1></div><button className="month glass" onClick={()=>setPanel('month')}>{monthLabel(id)}<ChevronDown size={15}/></button></div>
 {error&&<div className="alert" role="alert">{error}<button onClick={()=>setError('')} aria-label="关闭提示"><X size={16}/></button></div>}{notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="关闭通知"><X size={16}/></button></div>}{update&&<button className="notice" onClick={()=>void queue.current.then(()=>updateServiceWorker(true))}>新版已就绪 · 保存后更新</button>}
 {page===0&&<><section className="hero"><div className="hero-top"><span>生活预算剩余</span><span className="badge">{m.closed?'已月结':'进行中'}</span></div><div className={'hero-amount '+(c.remaining<0?'negative':'')}>{money(c.remaining)}</div><div className="progress"><i style={{width:`${Math.max(0,Math.min(100,c.remaining/Math.max(1,GROUPS.daily.reduce((n,k)=>n+m.plan[k],0))*100))}%`}}/></div><div className="hero-foot"><span>本月日常预算</span><strong>{money(GROUPS.daily.reduce((n,k)=>n+m.plan[k],0))}</strong></div></section><div className="two-cards"><section className="mini"><span><ArrowUpRight size={17}/>预计 surplus</span><strong>{money(c.surplus)}</strong><small>{m.closed?'已确认分配':'月结时进入 Funds'}</small></section><section className="mini blue"><span><ArrowDownLeft size={17}/>MV Savings</span><strong>{money(c.savings)}</strong><small>额外收入独立储蓄</small></section></div><p className="caption">{unconfirmed?`${unconfirmed} 项实际金额暂按 Plan 估算。点击项目确认或修改。`:'所有收入与固定项目已填写实际金额。'}</p>
 {Object.entries(GROUPS).map(([group,keys])=><section key={group}><div className="section-heading"><h2>{{income:'收入',personal:'Personal & Savings',fixed:'Fixed & Debt',daily:'日常预算'}[group]}</h2><span>PLAN / ACTUAL</span></div><div className="group">{keys.map(k=><button className="budget-row" key={k} onClick={()=>setPanel('line:'+k)}><span>{LABELS[k]}<small>{DAILY[k]?'普通预算流水':m.actual[k]===null?'暂估 · 点击确认':'已填写'}{group==='income'&&c.income>0?' · '+Math.round(actual(m,k)/c.income*100)+'%':''}</small></span><span className="numbers"><strong>{money(actual(m,k))}</strong><small>Plan {money(m.plan[k])}{group==='daily'?' · 余 '+money(m.plan[k]-actual(m,k)):''}</small></span><ChevronRight size={14}/></button>)}</div></section>)}</>}
 {page===1&&<><div className="search"><Search size={18}/><input aria-label="搜索流水" placeholder="搜索项目、类别" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="filters">{['all','ordinary',...FUNDS].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f==='all'?'全部':f==='ordinary'?'普通预算':f}</button>)}</div><div className="section-heading"><h2>{transactions.length} 笔流水</h2><span>{money(transactions.reduce((n,t)=>n+t.amount,0))}</span></div>{!transactions.length?<div className="empty"><List/><h2>给今天记上一笔</h2><p>点击下方 ＋，从金额开始。</p></div>:Array.from(new Set(transactions.map(t=>t.date))).map(date=><section key={date}><p className="date-label">{date}</p><div className="group">{transactions.filter(t=>t.date===date).map(t=><SwipeTransaction key={t.id} t={t} disabled={m.closed} edit={()=>openTx(t)} remove={()=>attempt(()=>{change(mm=>{mm.transactions=mm.transactions.filter(x=>x.id!==t.id);});setUndo({id,t});})}/>)}</div></section>)}</>}
 {page===2&&<><section className="hero funds-hero"><span>Virtual Funds · 可用余额</span><div className="hero-amount">{money(FUNDS.reduce((n,f)=>n+p.closing[f],0))}</div><p>支出即时扣除，surplus 在月结后分配。</p></section><div className="fund-grid">{FUNDS.map((f,i)=>{const Icon=fundIcons[i];return <button className="fund-card" key={f} onClick={()=>setPanel('fund:'+f)}><Icon size={22}/><span>{f}</span><strong className={p.closing[f]<0?'negative':''}>{money(p.closing[f])}</strong><small>{p.closing[f]<0?'负余额 · 待补足':`${m.shares[f]}% surplus allocation`}</small></button>;})}</div><div className="section-heading"><h2>独立储蓄</h2></div><div className="group">{row('MV Savings',money(p.savings),`本月 ${money(c.savings)}${m.closed?' 已结转':' 待月结'}`)}</div><div className="section-heading"><h2>资产与应收</h2></div><div className="group">{row('Receivables',money(p.receivables),'已月结还款后余额')}{row('DCA',m.assets.dca===null?'待确认':money(m.assets.dca),'月末余额',()=>setPanel('assets'))}{row('Money Market',m.assets.mm===null?'待确认':money(m.assets.mm),'月末余额',()=>setPanel('assets'))}</div></>}
 {page===3&&<><section className="close-intro"><div className="close-icon"><CheckCheck size={30}/></div><h2>{m.closed?'这个月，已收好。':'让这个月完整落定。'}</h2><p>核对四项，确认分配，再将月报存档。</p></section><div className="group">{(['income','fixed','ledger','assets'] as const).map((key,i)=><label className="row check-row" key={key}><span className="step">0{i+1}</span><span>{['确认实际收入','确认固定与 Personal 支出','核对所有流水','确认月末资产'][i]}<small>{['包含完整 MV Income','未填写项将按 Plan 确认','Fund 支出只计一次','填写 DCA 与 Money Market'][i]}</small></span><input type="checkbox" checked={m.checks[key]} disabled={m.closed} onChange={e=>modify(b=>{const mm=b.months[id];mm.checks[key]=e.target.checked;if(e.target.checked&&(key==='income'||key==='fixed'))for(const k of key==='income'?GROUPS.income:[...GROUPS.personal,...GROUPS.fixed,'streaming'])if(mm.actual[k]===null)mm.actual[k]=mm.plan[k];})}/></label>)}</div><button className="plain" onClick={()=>setPanel('assets')}>填写月末资产余额 <ChevronRight size={16}/></button><div className="section-heading"><h2>本月结算预览</h2><span>v{m.revision}</span></div><div className="group">{row('Household surplus',money(c.surplus))}{row('MV Savings',money(c.savings))}{row('Fund spending',money(c.totalFundSpend))}{row('流水差额',money(c.ledgerCheck))}</div><button className="primary" disabled={busy} onClick={()=>void doExport()}><Download size={18}/>{busy?'正在生成…':m.closed?'重新导出归档包':'确认月结并导出'}</button><p className="caption">ZIP 内含月报 XLSX、季度 CSV 和完整 JSON 备份。</p>{preparedArchive&&<a className="plain" href={preparedArchive.url} download={preparedArchive.name}>点击下载已生成的归档包</a>}<div className="group">{row('月结',m.closed?'已月结':'未月结')}{row('导出',m.exportedRevision===m.revision?'已生成':'未导出',m.exportedAt?new Date(m.exportedAt).toLocaleString('zh-CN'):undefined)}{row('Google Sheets 存档',m.archivedRevision===m.revision?'用户已确认':'待手动存档')}</div>{m.exportedRevision===m.revision&&m.archivedRevision!==m.revision&&<button className="plain" onClick={()=>setPanel('archive')}>确认已导入 Google Sheets</button>}{m.closed&&<button className="plain danger" onClick={()=>setPanel('reopen')}>更正这个月</button>}<div className="section-heading"><h2>月结记录</h2></div><div className="group">{book.history.length?book.history.slice().reverse().map((h,i)=>row(monthLabel(h.month)+' · v'+h.revision,new Date(h.closedAt).toLocaleDateString('zh-CN'),i===0?'最近一次确认':undefined)):<p className="inset">月结后会保留历史版本。</p>}</div></>}
 <footer className="app-footer">VEWU · {m.closed?'CLOSED':'IN PROGRESS'} · CAD<br/>数据保存在本机，定期备份。</footer></main><div className="dock"><nav className="glass" aria-label="主导航">{pages.map((name,i)=>{const Icon=icons[i];return <button key={name} aria-current={page===i?'page':undefined} onClick={()=>{setPage(i);window.scrollTo({top:0});}}>{page===i&&<motion.span layoutId="tab-pill" className="tab-pill" transition={{type:'spring',stiffness:460,damping:36}}/>}<Icon size={22}/><span>{name}</span></button>;})}</nav><button className="add glass" aria-label="新增记账" onClick={()=>openTx()}><Plus size={29}/></button></div>
 {undo&&<div className="undo" role="status">已删除流水<button onClick={()=>attempt(()=>{if(latest.current)commit(editMonth(latest.current,undo.id,mm=>mm.transactions.push(undo.t)));setUndo(null);})}>撤销</button><button onClick={()=>setUndo(null)} aria-label="关闭撤销"><X size={16}/></button></div>}{inputFile}
 <AnimatePresence>{panel&&<Sheet title={panel==='transaction'?(editing?'编辑流水':'记一笔'):panel.startsWith('line:')?LABELS[panel.slice(5)]:panel.startsWith('fund:')?panel.slice(5):({settings:'设置',month:'选择月份',assets:'月末资产',restore:'恢复账本',reopen:'更正月结',archive:'确认存档'} as Record<string,string>)[panel]||''} close={()=>setPanel(null)}>
 {error&&<p className="alert" role="alert">{error}</p>}
 {panel==='month'&&<div className="group">{MONTHS.map(mi=>row(shortMonth(mi)+' 2026',mi===id?'✓':'',book.months[mi].closed?'已月结':'进行中',()=>{setId(mi);setPanel(null);}))}</div>}
 {panel==='transaction'&&<TransactionForm month={id} transaction={editing} closed={m.closed} onSave={(t,again)=>attempt(()=>{change(mm=>{const idx=mm.transactions.findIndex(x=>x.id===t.id);if(idx<0)mm.transactions.push(t);else mm.transactions[idx]=t;});setNotice('已保存流水');if(!again)setPanel(null);else setEditing(null);})} onDelete={editing?()=>attempt(()=>{const t=editing;change(mm=>{mm.transactions=mm.transactions.filter(x=>x.id!==t.id);});setUndo({id,t});setPanel(null);}):undefined}/>}
 {panel.startsWith('line:')&&(()=>{const k=panel.slice(5);return <><p className="caption">{m.closed?'已月结；更正前需重新打开。':DAILY[k]?'Actual 由普通预算流水自动汇总。':'Actual 留空时按 Plan 估算。'}</p><fieldset disabled={m.closed}><AmountInput label="Plan" value={m.plan[k]} onChange={v=>attempt(()=>change(mm=>{mm.plan[k]=v??0;}))}/>{DAILY[k]?row('Actual',money(actual(m,k))):<AmountInput label="Actual" value={m.actual[k]} blank onChange={v=>attempt(()=>change(mm=>{mm.actual[k]=v;}))}/>}</fieldset><button className="primary" onClick={()=>setPanel(null)}>完成</button></>;})()}
 {panel.startsWith('fund:')&&(()=>{const f=panel.slice(5) as Fund;return <><div className="group">{row('Opening',money(p.opening[f]))}{row('Allocation',money(p.allocation[f]),m.closed?'已月结':'尚未分配')}{row('Spending',money(c.spent[f]))}{row('Closing',money(p.closing[f]))}</div><p className="caption">Opening + Allocation − Spending = Closing</p><div className="group">{m.transactions.filter(t=>t.fund===f).map(t=>row(t.item,money(t.amount),t.date,()=>openTx(t)))}</div></>;})()}
 {panel==='assets'&&<><fieldset disabled={m.closed}><AmountInput label="DCA" value={m.assets.dca} blank onChange={v=>attempt(()=>change(mm=>{mm.assets.dca=v;mm.checks.assets=false;}))}/><AmountInput label="Money Market" value={m.assets.mm} blank onChange={v=>attempt(()=>change(mm=>{mm.assets.mm=v;mm.checks.assets=false;}))}/></fieldset><button className="primary" onClick={()=>setPanel(null)}>完成</button></>}
 {panel==='settings'&&<><h3>外观</h3><label className="field">主题<select value={book.settings.theme} onChange={e=>modify(b=>{b.settings.theme=e.target.value as Book['settings']['theme'];})}><option value="system">跟随系统</option><option value="light">浅色</option><option value="dark">深色</option></select></label><label className="field">玻璃 · 清透至柔和<input aria-label="玻璃柔和程度" type="range" min="0" max="100" value={book.settings.glass} onChange={e=>modify(b=>{b.settings.glass=Number(e.target.value);})}/></label>{(['reduceTransparency','reduceMotion'] as const).map(k=><label className="field" key={k}>{k==='reduceMotion'?'减少动态效果':'减少透明度'}<input type="checkbox" checked={book.settings[k]} onChange={e=>modify(b=>{b.settings[k]=e.target.checked;})}/></label>)}<h3>{monthLabel(id)}分配比例</h3><p className="caption">正 surplus 按比例分配；负 surplus 全额扣入 General。</p><Shares month={m} onSave={shares=>attempt(()=>{change(mm=>{mm.shares=shares;});setNotice('分配比例已保存');})}/><h3>预算默认值</h3><p className="caption">在本月页面编辑各项 Plan，之后可以应用到后续未月结月份。</p><button className="plain" onClick={()=>attempt(()=>{let b=book;for(const mi of MONTHS.slice(MONTHS.indexOf(id)+1))if(!b.months[mi].closed)b=editMonth(b,mi,mm=>{mm.plan={...m.plan};});commit(b);setNotice('已将 Plan 应用到后续未月结月份');})}>应用本月 Plan 至后续月份</button><h3>备份与恢复</h3><button className="primary" onClick={()=>{download(JSON.stringify(book,null,2),'VEWU-backup.json');setNotice('备份已生成');}}>导出完整 JSON 备份</button><button className="plain" onClick={()=>file.current?.click()}>从 JSON 恢复账本</button><p className="caption">恢复会替换本机账本。首次导入私人账本后，数据不会上传至 GitHub。</p></>}
 {panel==='restore'&&preview&&<><p>将恢复 {MONTHS.reduce((n,mi)=>n+preview.months[mi].transactions.length,0)} 笔交易并替换本机账本。请先备份当前数据。</p><button className="plain" onClick={()=>download(JSON.stringify(book,null,2),'VEWU-before-restore.json')}>备份当前账本</button><button className="primary" onClick={()=>{commit(preview);setPreview(null);setPanel(null);setNotice('账本已恢复');}}>确认替换</button></>}
 {panel==='reopen'&&<><p>保留旧版本，并重新打开本月及后续月份。更正后需要按顺序月结、重新导出并存档。</p><button className="primary" onClick={()=>{commit(reopenMonth(book,id));setPanel(null);}}>重新打开并更正</button></>}
 {panel==='archive'&&<><p>请确认已将本次 CSV 替换导入 App Import，并检查月度页与季度汇总。此状态由你确认，应用不会自动读取 Google Sheets。</p><button className="primary" onClick={()=>{modify(b=>{b.months[id].archivedRevision=b.months[id].revision;b.months[id].needsArchive=false;b.months[id].archivedAt=new Date().toISOString();});setPanel(null);}}>已核对，标记存档</button></>}
 </Sheet>}</AnimatePresence></div></MotionConfig>;
}
function Shares({month,onSave}:{month:Month,onSave:(s:Month['shares'])=>void}){const [shares,setShares]=useState({...month.shares});return <form onSubmit={e=>{e.preventDefault();onSave(shares);}}><fieldset disabled={month.closed}>{FUNDS.map(f=><label className="field" key={f}>{f}<input aria-label={f+' allocation'} type="number" min="0" max="100" step="0.1" value={shares[f]} onChange={e=>setShares({...shares,[f]:Number(e.target.value)})}/></label>)}<button className="plain" type="submit">保存比例 · 合计 {Object.values(shares).reduce((a,b)=>a+b,0)}%</button></fieldset></form>;}
function TransactionForm({month,transaction,closed,onSave,onDelete}:{month:MonthId,transaction:Transaction|null,closed:boolean,onSave:(t:Transaction,again:boolean)=>void,onDelete?:()=>void}){const [amount,setAmount]=useState(transaction?String(dollars(transaction.amount)):''),[item,setItem]=useState(transaction?.item||''),[category,setCategory]=useState<Category>(transaction?.category||'Groceries'),[date,setDate]=useState(transaction?.date||todayIn(month)),[fund,setFund]=useState<Fund|''>(transaction?.fund||''),[again,setAgain]=useState(false);const [formError,setFormError]=useState('');const submit=(e:FormEvent)=>{e.preventDefault();try{const t={id:transaction?.id||crypto.randomUUID(),date,item,category,amount:cents(Number(amount)),fund};validateTransaction(t,month);onSave(t,again);setFormError('');if(again){setAmount('');setItem('');}}catch(e){setFormError((e as Error).message);}};return <form onSubmit={submit}>{formError&&<p className="alert" role="alert">{formError}</p>}<fieldset disabled={closed}><div className="amount-entry"><span>CAD</span><input aria-label="金额" inputMode="decimal" placeholder="0.00" pattern="-?[0-9]+([.][0-9]{1,2})?" required value={amount} onChange={e=>setAmount(e.target.value)}/></div><label className="field">项目<input aria-label="项目" placeholder="例如 Groceries" required maxLength={200} value={item} onChange={e=>setItem(e.target.value)}/></label><label className="field">类别<select value={category} onChange={e=>setCategory(e.target.value as Category)}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label className="field">日期<input aria-label="日期" type="date" min={month+'-01'} max={month+(month==='2026-11'?'-30':'-31')} required value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field">资金来源<select value={fund} onChange={e=>setFund(e.target.value as Fund| '')}><option value="">普通预算</option>{FUNDS.map(f=><option key={f}>{f}</option>)}</select></label><p className="caption">{fund?'从 '+fund+' 扣除，不再扣普通生活预算。':'计入当前类别的生活预算。退款请填负数。'}</p>{!transaction&&<label className="field">保存后继续记账<input type="checkbox" checked={again} onChange={e=>setAgain(e.target.checked)}/></label>}<button className="primary" type="submit"><Check size={19}/>保存这笔</button>{onDelete&&<button type="button" className="plain danger" onClick={onDelete}>删除流水</button>}</fieldset>{closed&&<p className="caption">已月结，请先在月结页面选择更正。</p>}</form>;}

function SwipeTransaction({t,edit,remove,disabled}:{t:Transaction,edit:()=>void,remove:()=>void,disabled:boolean}){const x=useMotionValue(0);return <div className="swipe-row"><div className="swipe-actions"><button onClick={edit}>编辑</button><button className="remove" disabled={disabled} onClick={remove}>删除</button></div><motion.button className="row transaction" style={{x,touchAction:'pan-y'}} drag="x" dragConstraints={{left:-128,right:0}} dragElastic={.06} onDragEnd={(_,info)=>{animate(x,info.offset.x+info.velocity.x*.1< -45?-128:0,{type:'spring',stiffness:420,damping:38});}} onClick={edit}><span className={'category-icon '+(t.fund?'funded':'')}><Wallet size={18}/></span><span>{t.item}<small>{t.category}{t.fund?' · '+t.fund:' · 普通预算'}</small></span><strong>{money(t.amount)}</strong></motion.button></div>;}
