import {useEffect,useRef,useState,type ReactNode,type FormEvent} from 'react';
import {AnimatePresence,motion,MotionConfig,useMotionValue,animate,useReducedMotion} from 'motion/react';
import {House,List,Layers,CheckCheck,Plus,Settings,ChevronDown,ChevronRight,X,Search,Plane,PawPrint,Shield,Wallet,Download,Check} from 'lucide-react';
import {useRegisterSW} from 'virtual:pwa-register/react';
import {MONTHS,FUNDS,GROUPS,DAILY,CATEGORIES,createBook,calc,allocate,position,investmentPosition,money,actual,shortMonth,monthLabel,dollars,editMonth,applyScoped,closeMonth,reopenMonth,touch,todayIn,localDate,backupStale,reminder,parseAmount,validateTransaction,type Book,type MonthId,type Month,type Transaction,type Fund,type Category,type Language,type Scope} from './model';
import {loadBook,saveBook,replaceBook} from './storage';
import {prepareBackup,importCSV,download} from './export';
import {translator,label,errorText} from './i18n';
import {Sheet} from './Sheet';
import {observeViewport} from './viewport';
const icons=[House,List,Layers,CheckCheck],fundIcons=[Shield,Plane,PawPrint,Wallet];
const spring={type:'spring' as const,stiffness:420,damping:42};
function AmountField({name,value,set,nullable=false,language,busy=false}:{name:string,value:string,set:(v:string)=>void,nullable?:boolean,language:Language,busy?:boolean}) {
  return <label className="field"><span>{name}</span><input aria-label={name} readOnly={busy} inputMode="decimal" value={value} onChange={e=>set(e.target.value)} placeholder={nullable?translator(language)('未确认','Unconfirmed'):''}/></label>;
}
function ScopePicker({value,set,language,busy=false}:{value:Scope,set:(v:Scope)=>void,language:Language,busy?:boolean}) {
  const t=translator(language);return <fieldset className="scope" disabled={busy}><legend>{t('修改范围','Apply changes to')}</legend>{(['month','future'] as const).map(s=><label key={s}><input type="radio" name="scope" value={s} checked={value===s} onChange={()=>set(s)}/>{s==='month'?t('仅本月','This month only'):t('本月及后续未月结月份','This and future open months')}</label>)}</fieldset>;
}
export default function App() {
  const [book,setBook]=useState<Book|null>(null),[loading,setLoading]=useState(true),[failedLoad,setFailedLoad]=useState(false),[language,setLanguage]=useState<Language>('zh');
  const [page,setPage]=useState(0),[id,setId]=useState<MonthId>(()=>{const month=localDate().slice(0,7) as MonthId;return MONTHS.includes(month)?month:month<'2026-10'?'2026-10':'2026-12';}),[panel,setPanel]=useState<string|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[editing,setEditing]=useState<Transaction|null>(null),[undo,setUndo]=useState<{id:MonthId,t:Transaction}|null>(null),[preview,setPreview]=useState<Book|null>(null),[prepared,setPrepared]=useState<{url:string,name:string}|null>(null),[clock,setClock]=useState(new Date());
  const latest=useRef<Book|null>(null),queue=useRef(Promise.resolve()),file=useRef<HTMLInputElement>(null);const t=translator(language),ml=(mi:MonthId)=>language==='zh'?monthLabel(mi):shortMonth(mi);
  const pages=[t('本月','Month'),t('记账','Ledger'),t('资金','Funds'),t('月结','Close')];
  const {needRefresh:[update],updateServiceWorker}=useRegisterSW();
  useEffect(()=>{loadBook().then(b=>{latest.current=b;setBook(b);if(b)setLanguage(b.settings.language||'zh');}).catch(e=>{setFailedLoad(true);setError(errorText(e,'zh'));}).finally(()=>setLoading(false));},[]);
  useEffect(()=>{document.documentElement.lang=language==='zh'?'zh-CN':'en';setNotice('');setError('');},[language]);
  useEffect(()=>()=>{if(prepared)URL.revokeObjectURL(prepared.url);},[prepared]);
  useEffect(()=>{const tick=()=>setClock(new Date());const timer=setInterval(tick,60000);document.addEventListener('visibilitychange',tick);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',tick);};},[]);
  useEffect(observeViewport,[]);
  const commit=async(b:Book,replace=false)=>{
    setBusy(true);const task=queue.current.catch(()=>{}).then(()=>replace?replaceBook(b):saveBook(b));queue.current=task;
    try{await task;latest.current=b;setBook(b);setLanguage(b.settings.language||'zh');setPrepared(null);}finally{setBusy(false);}
  };
  const attempt=async(fn:()=>Promise<void>|void)=>{try{setError('');await fn();return true;}catch(e){setError(errorText(e,language));return false;}};
  const change=async(fn:(m:Month)=>void)=>{if(latest.current)await commit(editMonth(latest.current,id,fn));};
  const modify=async(fn:(b:Book)=>void)=>{if(latest.current){const b=touch(latest.current);fn(b);await commit(b);}};
  const exportBackup=async()=>{if(!latest.current)return;const result=prepareBackup(latest.current);const name=`VEWU-2026-Q4-${localDate()}.csv`;const url=download(result.text,name);await commit(result.book);setPrepared({url,name});setNotice(t('CSV 已生成','CSV generated'));};
  const restore=async(f:File)=>{await attempt(async()=>{if(f.size>20_000_000)throw new Error('large');setPreview(importCSV(await f.text()));setPanel('restore');});};
  const fileInput=<input ref={file} type="file" accept=".csv,text/csv" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void restore(f);e.target.value='';}}/>;
  const restoreContent=preview&&<><p className="inset">{t('替换本机账本：','Replace the local ledger: ')}{MONTHS.reduce((n,mi)=>n+preview.months[mi].transactions.length,0)} {t('笔交易','transactions')}</p><button className="primary" disabled={busy} onClick={()=>void attempt(async()=>{await commit(preview,true);setPreview(null);setPanel(null);setNotice(t('账本已恢复','Ledger restored'));})}>{t('确认替换','Confirm replacement')}</button></>;
  if(loading)return <main className="welcome"><p>{t('正在打开账本…','Opening ledger…')}</p></main>;
  if(failedLoad)return <main className="welcome"><h1>VEWU Finance</h1><p role="alert">{error}</p><button className="primary" onClick={()=>window.location.reload()}>{t('重新加载','Reload')}</button></main>;
  if(!book)return <><main className="welcome"><span className="eyebrow">OCT — DEC 2026</span><h1>VEWU Finance</h1><button className="primary" disabled={busy} onClick={()=>file.current?.click()}>{t('导入 CSV','Import CSV')}</button><button className="plain" disabled={busy} onClick={()=>void attempt(()=>commit(createBook()))}>{t('创建账本','Create ledger')}</button><button className="plain" onClick={()=>setLanguage(language==='zh'?'en':'zh')}>{language==='zh'?'English':'中文'}</button>{error&&<p role="alert">{error}</p>}</main>{fileInput}{panel==='restore'&&<Sheet title={t('导入 CSV','Import CSV')} language={language} close={()=>setPanel(null)}>{restoreContent}{error&&<p role="alert">{error}</p>}</Sheet>}</>;
  const m=book.months[id],c=calc(book,id),p=position(book,id),assetOpening=investmentPosition(book,id),r=reminder(book,clock);
  const transactions=m.transactions.filter(tx=>(filter==='all'||filter==='ordinary'&&!tx.fund||tx.fund===filter)&&`${tx.item} ${label(tx.category,language)} ${label(tx.fund,language)}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date));
  const openTx=(tx:Transaction|null=null)=>{setEditing(tx);setError('');setPanel('transaction');};
  const row=(name:string,value:string,sub?:string,action?:()=>void)=><button className="row" onClick={action} disabled={!action}><span>{name}{sub&&<small>{sub}</small>}</span><strong>{value}</strong>{action&&<ChevronRight size={16}/>}</button>;
  const group=(name:string,keys:readonly string[])=> <section key={name}><div className="section-heading"><h2>{name}</h2><span>Plan / Actual</span></div><div className="group">{keys.map(k=><button className="budget-row" key={k} onClick={()=>{setError('');setPanel('line:'+k);}}><span>{label(k,language)}{!DAILY[k]&&<small>{m.actual[k]===null?t('暂估','Estimated'):t('已确认','Confirmed')}</small>}</span><span className="numbers"><strong>{money(actual(m,k))}</strong><small>Plan {money(m.plan[k])}{DAILY[k]?` · ${t('余','Left')} ${money(m.plan[k]-actual(m,k))}`:''}</small></span><ChevronRight size={14}/></button>)}</div></section>;
  const backupButtons=<><button className="primary" disabled={busy} onClick={()=>void attempt(exportBackup)}><Download size={18}/>Export CSV</button><button className="plain" disabled={busy} onClick={()=>file.current?.click()}>Import CSV</button><div className={'backup-status '+(backupStale(book,clock)?'stale':'')}>Last backup <span>{book.lastBackup?new Date(book.lastBackup).toLocaleString(language==='zh'?'zh-CN':'en-CA'):t('尚未备份','Never')}</span></div>{prepared&&<a className="plain" href={prepared.url} download={prepared.name}>{t('下载 CSV','Download CSV')}</a>}</>;
  const title=panel==='transaction'?(editing?t('编辑流水','Edit transaction'):t('记一笔','Add transaction')):panel?.startsWith('line:')?label(panel.slice(5),language):panel?.startsWith('fund:')?label(panel.slice(5),language):({settings:t('设置','Settings'),month:t('选择月份','Choose month'),assets:t('月末资产','Closing assets'),restore:t('导入 CSV','Import CSV'),reopen:t('更正月结','Correct month'),opening:t('期初余额','Opening balances')} as Record<string,string>)[panel||'']||'';
  return <MotionConfig reducedMotion="user"><div className="app"><header className="topbar"><span className="wordmark">VEWU<span> FINANCE</span></span><button className="round glass" aria-label={t('设置','Settings')} onClick={()=>{setError('');setPanel('settings');}}><Settings size={21}/></button></header><motion.main key={page} initial={{opacity:.9}} animate={{opacity:1}} transition={{duration:.15}}>
    <div className="title-line"><div><span className="eyebrow">2026 · OCT–DEC</span><h1>{page===0?ml(id):pages[page]}</h1></div><button className="month glass" onClick={()=>setPanel('month')}>{ml(id)}<ChevronDown size={15}/></button></div>
    {error&&<div className="alert" role="alert">{error}<button onClick={()=>setError('')} aria-label={t('关闭提示','Dismiss error')}><X size={16}/></button></div>}
    {notice&&<div className="notice toast" role="status">{notice}<button onClick={()=>setNotice('')} aria-label={t('关闭通知','Dismiss notice')}><X size={16}/></button></div>}
    {update&&<button className="notice" disabled={busy} onClick={()=>void attempt(async()=>{await queue.current;await updateServiceWorker(true);})}>{t('新版已就绪 · 更新','Update ready · Install')}</button>}
    {r&&<div className="reminder"><button className="reminder-action" onClick={()=>{setId(r.month);setPage(3);}}>{ml(r.month)} · {r.reason==='close'?t('待月结','Close needed'):t('当前版本待备份','Current version needs backup')}</button><button aria-label={t('今天不再提醒','Dismiss for today')} onClick={()=>void attempt(()=>modify(b=>{b.reminderDismissedOn=localDate(clock);}))}><X size={17}/></button></div>}
    {page===0&&<><section className="hero"><div className="hero-top"><span>{t('生活预算剩余','Lifestyle Remaining')}</span><span className="badge">{m.closed?t('已月结','Closed'):t('进行中','Open')}</span></div><div className={'hero-amount '+(c.remaining<0?'negative':'')}>{money(c.remaining)}</div><div className="progress"><i style={{width:`${Math.max(0,Math.min(100,c.remaining/Math.max(1,GROUPS.daily.reduce((n,k)=>n+m.plan[k],0))*100))}%`}}/></div><div className="hero-foot"><span>{t('生活预算','Lifestyle Plan')}</span><strong>{money(GROUPS.daily.reduce((n,k)=>n+m.plan[k],0))}</strong></div></section>
      <div className="two-cards"><section className="mini"><span>{t('计划结余','Plan Surplus')}</span><strong className={c.surplusPlan<0?'negative':''}>{money(c.surplusPlan)}</strong></section><section className="mini savings"><span>MV Savings</span><strong>{money(c.savings)}</strong></section></div>
      {group(t('日常预算','Lifestyle'),GROUPS.daily)}{group(t('收入','Income'),GROUPS.income)}{group(t('个人预算与投资','Personal & Investment'),GROUPS.personal)}
      <FixedSection title={t('固定支出与债务','Fixed & Debt')} total={money(GROUPS.fixed.reduce((n,k)=>n+actual(m,k),0))}>{group(t('固定支出','Fixed'),GROUPS.fixed)}</FixedSection>
    </>}
    {page===1&&<><div className="search"><Search size={18}/><input aria-label={t('搜索流水','Search transactions')} placeholder={t('搜索流水','Search transactions')} value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="filters">{['all','ordinary',...FUNDS].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f==='all'?t('全部','All'):f==='ordinary'?t('普通预算','Lifestyle'):label(f,language)}</button>)}</div><div className="section-heading"><h2>{transactions.length} {t('笔流水','transactions')}</h2><span>{money(transactions.reduce((n,tx)=>n+tx.amount,0))}</span></div>{!transactions.length?<div className="empty"><List/><p>{t('点击 ＋ 记账','Tap + to add a transaction')}</p></div>:Array.from(new Set(transactions.map(tx=>tx.date))).map(date=><section key={date}><p className="date-label">{date}</p><div className="group">{transactions.filter(tx=>tx.date===date).map(tx=><SwipeTransaction key={tx.id} tx={tx} language={language} disabled={m.closed||busy} edit={()=>openTx(tx)} remove={()=>void attempt(async()=>{await change(mm=>{mm.transactions=mm.transactions.filter(x=>x.id!==tx.id);});setUndo({id,t:tx});})}/>)}</div></section>)}</>}
    {page===2&&<><section className="hero"><div className="hero-top">{t('Funds 可用余额','Available Funds')}</div><div className="hero-amount">{money(FUNDS.reduce((n,f)=>n+p.closing[f],0))}</div></section><div className="fund-grid">{FUNDS.map((f,i)=>{const Icon=fundIcons[i];return <button className="fund-card" key={f} onClick={()=>setPanel('fund:'+f)}><Icon size={22}/><span>{label(f,language)}</span><strong className={p.closing[f]<0?'negative':''}>{money(p.closing[f])}</strong><small>{p.closing[f]<0?t('负余额','Overdrawn'):`${m.shares[f]}%`}</small></button>;})}</div><div className="section-heading"><h2>{t('独立储蓄','Savings')}</h2></div><div className="group">{row('MV Savings',money(p.savings),m.closed?t('已结转','Posted'):t('本月待结转','Pending this month')+' '+money(c.savings))}</div><div className="section-heading"><h2>{t('资产与应收','Assets & Receivables')}</h2></div><div className="group">{row(t('应收款','Receivables'),money(p.receivables))}{row('DCA',money(m.assets.dca??assetOpening.dca),m.assets.dca===null?t('期初余额','Opening balance'):t('月末余额','Closing balance'),()=>setPanel('assets'))}{row('Money Market',money(m.assets.mm??assetOpening.mm),m.assets.mm===null?t('期初余额','Opening balance'):t('月末余额','Closing balance'),()=>setPanel('assets'))}{row(t('投资合计','Investment Total'),money((m.assets.dca??assetOpening.dca)+(m.assets.mm??assetOpening.mm)))}</div></>}
    {page===3&&<><div className="section-heading"><h2>{m.closed?t('已月结','Closed'):t('月结核对','Monthly checks')}</h2><span>v{m.revision}</span></div><div className="group">{(['income','fixed','ledger','assets'] as const).map((key,i)=><label className="row check-row" key={key}><span className="step">0{i+1}</span><span>{[t('确认收入','Confirm income'),t('确认固定与个人支出','Confirm fixed & personal'),t('核对流水','Check transactions'),t('确认月末资产','Confirm closing assets')][i]}</span><input aria-label={[t('确认收入','Confirm income'),t('确认固定与个人支出','Confirm fixed & personal'),t('核对流水','Check transactions'),t('确认月末资产','Confirm closing assets')][i]} type="checkbox" checked={m.checks[key]} disabled={m.closed||busy} onChange={e=>{const checked=e.target.checked;void attempt(()=>modify(b=>{const mm=b.months[id];if(checked&&(key==='income'||key==='fixed'))for(const k of key==='income'?GROUPS.income:[...GROUPS.personal,...GROUPS.fixed])if(mm.actual[k]===null)mm.actual[k]=mm.plan[k];mm.checks[key]=checked;mm.revision++;mm.exportedRevision=null;}));}}/></label>)}</div><button className="plain" onClick={()=>setPanel('assets')}>{t('填写月末资产','Enter closing assets')}<ChevronRight size={16}/></button><div className="section-heading"><h2>{t('结算预览','Closing preview')}</h2></div><div className="group">{row(t('实际结余','Actual Surplus'),money(c.surplus))}{row('MV Savings',money(c.savings))}{row(t('Fund 支出','Fund Spending'),money(c.totalFundSpend))}{row(t('流水差额','Ledger difference'),money(c.ledgerCheck))}{FUNDS.map(f=>row(label(f,language),money(m.closed?p.allocation[f]:allocatePreview(book,id,f))))}</div>
      {!m.closed&&<button className="primary" disabled={busy} onClick={()=>void attempt(async()=>{await commit(closeMonth(latest.current!,id));setNotice(t('月结已确认','Month closed'));})}><CheckCheck size={18}/>{t('确认月结','Confirm close')}</button>}{m.closed&&<button className="plain danger" disabled={busy} onClick={()=>setPanel('reopen')}>{t('更正本月','Correct this month')}</button>}
      {backupButtons}<div className="section-heading"><h2>{t('历史版本','History')}</h2></div><div className="group">{book.history.length?book.history.slice().reverse().map((h,i)=><div key={i}>{row(ml(h.month)+' · v'+h.revision,new Date(h.closedAt).toLocaleDateString(language==='zh'?'zh-CN':'en-CA'))}</div>):<p className="inset">{t('暂无月结记录','No closed versions')}</p>}</div>
    </>}
  </motion.main><div className="dock"><nav className="glass" aria-label={t('主导航','Main navigation')}>{pages.map((name,i)=>{const Icon=icons[i];return <button key={i} aria-current={page===i?'page':undefined} onClick={()=>{setPage(i);window.scrollTo({top:0});}}>{page===i&&<motion.span layoutId="tab-pill" className="tab-pill" transition={spring}/>}<Icon size={22}/><span>{name}</span></button>;})}</nav><button className="add glass" aria-label={t('新增记账','Add transaction')} disabled={busy||m.closed} onClick={()=>openTx()}><Plus size={29}/></button></div>
    {undo&&<div className="undo" role="status">{t('已删除流水','Transaction deleted')}<button disabled={busy} onClick={()=>void attempt(async()=>{await commit(editMonth(latest.current!,undo.id,mm=>mm.transactions.push(undo.t)));setUndo(null);})}>{t('撤销','Undo')}</button><button onClick={()=>setUndo(null)} aria-label={t('关闭撤销','Dismiss undo')}><X size={16}/></button></div>}{fileInput}
    <AnimatePresence>{panel&&<Sheet key="editor" contentKey={panel} title={title} language={language} close={()=>{if(!busy){setPanel(null);setError('');}}}>
      {error&&<p className="alert" role="alert">{error}</p>}
      {panel==='month'&&<div className="group">{MONTHS.map(mi=><div key={mi}>{row(ml(mi)+' 2026',mi===id?'✓':'',book.months[mi].closed?t('已月结','Closed'):t('进行中','Open'),()=>{setId(mi);setPanel(null);})}</div>)}</div>}
      {panel==='transaction'&&<TransactionForm key={editing?.id||'new'} month={id} transaction={editing} closed={m.closed} busy={busy} language={language} onSave={async(tx,again)=>{const ok=await attempt(async()=>{await change(mm=>{const idx=mm.transactions.findIndex(x=>x.id===tx.id);if(idx<0)mm.transactions.push(tx);else mm.transactions[idx]=tx;});setNotice(t('流水已保存','Transaction saved'));if(!again)setPanel(null);});return ok;}} onDelete={editing?()=>void attempt(async()=>{const tx=editing;await change(mm=>{mm.transactions=mm.transactions.filter(x=>x.id!==tx.id);});setUndo({id,t:tx});setPanel(null);}):undefined}/>}
      {panel.startsWith('line:')&&<LineEditor field={panel.slice(5)} month={m} language={language} busy={busy} onSave={(plan,value,scope)=>attempt(async()=>{const k=panel.slice(5);let b=latest.current!;if(plan!==m.plan[k]||scope==='future')b=applyScoped(b,id,scope,mm=>{mm.plan[k]=plan;});if(!DAILY[k]&&value!==m.actual[k])b=editMonth(b,id,mm=>{mm.actual[k]=value;});await commit(b);setPanel(null);})}/>}
      {panel.startsWith('fund:')&&(()=>{const f=panel.slice(5) as Fund;return <><div className="group">{row(t('期初','Opening'),money(p.opening[f]))}{row(t('已分配','Allocation'),money(p.allocation[f]))}{row(t('支出','Spending'),money(c.spent[f]))}{row(t('期末','Closing'),money(p.closing[f]))}</div><div className="section-heading"><h2>{t('相关流水','Transactions')}</h2></div><div className="group">{m.transactions.filter(tx=>tx.fund===f).map(tx=><div key={tx.id}>{row(tx.item,money(tx.amount),tx.date,()=>openTx(tx))}</div>)}</div></>;})()}
      {panel==='assets'&&<AssetEditor month={m} busy={busy} language={language} onSave={async(assets)=>attempt(async()=>{await change(mm=>{mm.assets=assets;});setPanel(null);})}/>}
      {panel==='settings'&&<><label className="field">{t('语言','Language')}<select aria-label={t('语言','Language')} value={language} disabled={busy} onChange={e=>{const lang=e.target.value as Language;void attempt(()=>modify(b=>{b.settings.language=lang;}));}}><option value="zh">中文</option><option value="en">English</option></select></label><h3>{ml(id)} · {t('分配比例','Allocation')}</h3><Shares month={m} language={language} busy={busy} onSave={(shares,scope)=>attempt(async()=>{await commit(applyScoped(latest.current!,id,scope,mm=>{mm.shares={...shares};}));setNotice(t('比例已保存','Allocation saved'));})}/><button className="plain" onClick={()=>setPanel('opening')}>{t('期初余额','Opening balances')}<ChevronRight size={16}/></button><h3>{t('备份','Backup')}</h3>{backupButtons}</>}
      {panel==='opening'&&<OpeningEditor book={book} language={language} busy={busy} onSave={opening=>attempt(async()=>{if(MONTHS.some(mi=>book.months[mi].closed))throw new Error('closed');await modify(b=>{b.opening=opening;});setPanel(null);})}/>}
      {panel==='restore'&&restoreContent}
      {panel==='reopen'&&<><p className="inset">{t('保留历史版本，并重新打开本月及后续月份。','Keep historical versions and reopen this and later months.')}</p><button className="primary" disabled={busy} onClick={()=>void attempt(async()=>{await commit(reopenMonth(latest.current!,id));setPanel(null);})}>{t('重新打开','Reopen')}</button></>}
    </Sheet>}</AnimatePresence>
  </div></MotionConfig>;
}
function allocatePreview(book:Book,id:MonthId,fund:Fund){return allocate(calc(book,id).surplus,book.months[id].shares)[fund];}
function LineEditor({field,month,language,busy,onSave}:{field:string,month:Month,language:Language,busy:boolean,onSave:(plan:number,value:number|null,scope:Scope)=>Promise<boolean>}) {
  const [plan,setPlan]=useState(dollars(month.plan[field]).toFixed(2)),[value,setValue]=useState(month.actual[field]===null||DAILY[field]?'':dollars(month.actual[field]!).toFixed(2)),[scope,setScope]=useState<Scope>('month'),[error,setError]=useState('');const t=translator(language);
  const submit=async(e:FormEvent)=>{e.preventDefault();if(busy)return;try{await onSave(parseAmount(plan)!,DAILY[field]?null:parseAmount(value,true),scope);setError('');}catch(err){setError(errorText(err,language));}};
  return <form onSubmit={e=>void submit(e)}><fieldset disabled={month.closed} aria-busy={busy}><AmountField name="Plan" value={plan} set={setPlan} busy={busy} language={language}/>{DAILY[field]?<div className="inset">Actual {money(actual(month,field))}</div>:<AmountField name="Actual" value={value} set={setValue} nullable busy={busy} language={language}/>}<ScopePicker value={scope} set={setScope} language={language} busy={busy}/><button className="primary" disabled={busy} type="submit">{t('保存','Save')}</button></fieldset>{month.closed&&<p className="inset">{t('请先重新打开此月份','Reopen this month first')}</p>}{error&&<p className="alert" role="alert">{error}</p>}</form>;
}
function Shares({month,language,busy,onSave}:{month:Month,language:Language,busy:boolean,onSave:(s:Month['shares'],scope:Scope)=>Promise<boolean>}) {
  const [shares,setShares]=useState(Object.fromEntries(FUNDS.map(f=>[f,String(month.shares[f])])) as Record<Fund,string>),[scope,setScope]=useState<Scope>('month');const t=translator(language);
  return <form onSubmit={e=>{e.preventDefault();if(busy)return;void onSave(Object.fromEntries(FUNDS.map(f=>[f,shares[f].trim()===''?NaN:Number(shares[f])])) as Month['shares'],scope);}}><fieldset disabled={month.closed} aria-busy={busy}>{FUNDS.map(f=><label className="field" key={f}><span>{label(f,language)} %</span><input readOnly={busy} aria-label={label(f,language)+' %'} inputMode="decimal" value={shares[f]} onChange={e=>setShares({...shares,[f]:e.target.value})}/></label>)}<ScopePicker value={scope} set={setScope} language={language} busy={busy}/><button className="plain" disabled={busy} type="submit">{t('保存比例','Save allocation')}</button></fieldset></form>;
}
function AssetEditor({month,language,busy,onSave}:{month:Month,language:Language,busy:boolean,onSave:(a:Month['assets'])=>Promise<boolean>}) {
  const [dca,setDca]=useState(month.assets.dca===null?'':dollars(month.assets.dca).toFixed(2)),[mm,setMm]=useState(month.assets.mm===null?'':dollars(month.assets.mm).toFixed(2)),[error,setError]=useState('');const t=translator(language);
  return <form onSubmit={e=>{e.preventDefault();if(busy)return;try{void onSave({dca:parseAmount(dca,true),mm:parseAmount(mm,true)});}catch(err){setError(errorText(err,language));}}}><fieldset disabled={month.closed} aria-busy={busy}><AmountField name="DCA" value={dca} set={setDca} nullable busy={busy} language={language}/><AmountField name="Money Market" value={mm} set={setMm} nullable busy={busy} language={language}/><button className="primary" disabled={busy} type="submit">{t('保存','Save')}</button></fieldset>{error&&<p role="alert" className="alert">{error}</p>}</form>;
}
function OpeningEditor({book,language,busy,onSave}:{book:Book,language:Language,busy:boolean,onSave:(o:Book['opening'])=>Promise<boolean>}) {
  const initial={...book.opening.funds,savings:book.opening.savings,receivables:book.opening.receivables,dca:book.opening.dca,mm:book.opening.mm};
  const [values,setValues]=useState(Object.fromEntries(Object.entries(initial).map(([k,v])=>[k,dollars(v).toFixed(2)]))),[error,setError]=useState('');const t=translator(language);
  return <form onSubmit={e=>{e.preventDefault();if(busy)return;try{const nums=Object.fromEntries(Object.entries(values).map(([k,v])=>[k,parseAmount(v)!]));void onSave({funds:Object.fromEntries(FUNDS.map(f=>[f,nums[f]])) as Book['opening']['funds'],savings:nums.savings,receivables:nums.receivables,dca:nums.dca,mm:nums.mm});}catch(err){setError(errorText(err,language));}}}><fieldset disabled={MONTHS.some(mi=>book.months[mi].closed)} aria-busy={busy}>{Object.keys(initial).map(k=><AmountField key={k} name={k==='savings'?'MV Savings':k==='receivables'?t('应收款','Receivables'):k==='dca'?'DCA':k==='mm'?'Money Market':label(k,language)} value={values[k]} set={v=>setValues({...values,[k]:v})} busy={busy} language={language}/>)}<button className="primary" disabled={busy} type="submit">{t('保存','Save')}</button></fieldset>{error&&<p role="alert" className="alert">{error}</p>}</form>;
}
function TransactionForm({month,transaction,closed,busy,language,onSave,onDelete}:{month:MonthId,transaction:Transaction|null,closed:boolean,busy:boolean,language:Language,onSave:(t:Transaction,again:boolean)=>Promise<boolean>,onDelete?:()=>void}) {
  const [amount,setAmount]=useState(transaction?dollars(transaction.amount).toFixed(2):''),[item,setItem]=useState(transaction?.item||''),[category,setCategory]=useState<Category>(transaction?.category||'Groceries'),[date,setDate]=useState(transaction?.date||todayIn(month)),[fund,setFund]=useState<Fund|''>(transaction?.fund||''),[again,setAgain]=useState(false),[error,setError]=useState('');const t=translator(language);
  const submit=async(e:FormEvent)=>{e.preventDefault();if(busy)return;try{const tx={id:transaction?.id||crypto.randomUUID(),date,item,category,amount:parseAmount(amount)!,fund};validateTransaction(tx,month);if(await onSave(tx,again)){setError('');if(again){setAmount('');setItem('');}}}catch(err){setError(errorText(err,language));}};
  return <form onSubmit={e=>void submit(e)}>{error&&<p className="alert" role="alert">{error}</p>}<fieldset disabled={closed} aria-busy={busy}><div className="amount-entry"><span>CAD</span><input readOnly={busy} aria-label={t('金额','Amount')} inputMode="decimal" required value={amount} onChange={e=>setAmount(e.target.value)}/></div><label className="field"><span>{t('项目','Item')}</span><input readOnly={busy} aria-label={t('项目','Item')} required maxLength={200} value={item} onChange={e=>setItem(e.target.value)}/></label><label className="field"><span>{t('类别','Category')}</span><select disabled={busy} aria-label={t('类别','Category')} value={category} onChange={e=>setCategory(e.target.value as Category)}>{CATEGORIES.map(cat=><option key={cat} value={cat}>{label(cat,language)}</option>)}</select></label><label className="field"><span>{t('日期','Date')}</span><input readOnly={busy} aria-label={t('日期','Date')} type="date" min={month+'-01'} max={month+(month==='2026-11'?'-30':'-31')} required value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field"><span>{t('资金来源','Funding source')}</span><select disabled={busy} aria-label={t('资金来源','Funding source')} value={fund} onChange={e=>setFund(e.target.value as Fund|'')}><option value="">{t('普通预算','Lifestyle')}</option>{FUNDS.map(f=><option key={f} value={f}>{label(f,language)}</option>)}</select></label>{!transaction&&<label className="field"><span>{t('连续记账','Keep adding')}</span><input disabled={busy} type="checkbox" checked={again} onChange={e=>setAgain(e.target.checked)}/></label>}<button className="primary" disabled={busy} type="submit"><Check size={19}/>{t('保存','Save')}</button>{onDelete&&<button type="button" className="plain danger" disabled={busy} onClick={onDelete}>{t('删除流水','Delete transaction')}</button>}</fieldset>{closed&&<p className="inset">{t('请先重新打开此月份','Reopen this month first')}</p>}</form>;
}
function SwipeTransaction({tx,language,edit,remove,disabled}:{tx:Transaction,language:Language,edit:()=>void,remove:()=>void,disabled:boolean}) {
  const x=useMotionValue(0),reduced=useReducedMotion(),t=translator(language);return <div className="swipe-row"><div className="swipe-actions"><button onClick={edit}>{t('编辑','Edit')}</button><button className="remove" disabled={disabled} onClick={remove}>{t('删除','Delete')}</button></div><motion.button className="row transaction" style={{x,touchAction:'pan-y'}} drag={disabled?false:'x'} dragConstraints={{left:-144,right:0}} dragElastic={reduced?0:.04} onDragEnd={(_,info)=>{animate(x,x.get()+info.velocity.x*.12< -60?-144:0,reduced?{duration:0}:{...spring,velocity:info.velocity.x});}} onClick={edit}><span className="category-icon"><Wallet size={18}/></span><span>{tx.item}<small>{label(tx.category,language)} · {tx.fund?label(tx.fund,language):t('普通预算','Lifestyle')}</small></span><strong>{money(tx.amount)}</strong></motion.button></div>;
}

function FixedSection({title,total,children}:{title:string,total:string,children:ReactNode}) {const [open,setOpen]=useState(false),reduced=useReducedMotion();return <section className="fixed"><button className="fixed-toggle" aria-expanded={open} onClick={()=>setOpen(!open)}>{title}<strong>{total}</strong><ChevronDown size={18} style={{rotate:open?'180deg':'0deg'}}/></button><AnimatePresence initial={false}>{open&&<motion.div key="fixed" initial={reduced?false:{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} transition={reduced?{duration:0}:spring} style={{overflow:'hidden'}}>{children}</motion.div>}</AnimatePresence></section>;}
