import {describe,it,expect} from 'vitest';
import {blankBook,migrateBook,calc,changeCategory,confirmPlan,actual,closeMonth,groupTotal,percentage,allocate,validateBook,type CategoryDefinition,type Book} from './model';
import {csv,importCSV} from './export';
const custom=(group:CategoryDefinition['group']='daily'):CategoryDefinition=>({id:'custom-test',name:'Coffee & Tea',group,mode:group==='daily'?'ledger':'manual',archived:false,core:false});
function legacy(){const b=blankBook();b.schema=2;for(const m of Object.values(b.months)){delete m.categories;delete m.expanded;}b.months['2026-10'].plan.pw=615000;b.months['2026-10'].actual.mv=null;b.months['2026-10'].transactions.push({id:'old',date:'2026-10-02',item:'Old groceries',category:'Groceries',amount:5247,fund:''});return b;}
describe('category catalog and old ledgers',()=>{
 it('migrates V2 without rewriting monetary fields, transaction category values, IDs or nulls',()=>{const old=legacy(),next=migrateBook(old);expect(next.schema).toBe(3);for(const id of Object.keys(old.months) as (keyof Book['months'])[]){const {categories,expanded,...rest}=next.months[id];expect(rest).toEqual(old.months[id]);expect(categories?.find(c=>c.id==='groceries')?.transactionKey).toBe('Groceries');}expect(calc(next,'2026-10')).toEqual(calc(old,'2026-10'));expect(old.schema).toBe(2);});
 it('adds a ledger category, counts its ordinary spending and excludes fund spending once',()=>{let b=changeCategory(blankBook(),'2026-10','month',custom());const m=b.months['2026-10'];m.plan['custom-test']=10000;m.transactions.push({id:'coffee',date:'2026-10-04',item:'Coffee',category:'custom-test',amount:1234,fund:''},{id:'fund',date:'2026-10-04',item:'Fund coffee',category:'custom-test',amount:900,fund:'General'});b=validateBook(b);expect(actual(m,'custom-test')).toBe(1234);expect(calc(b,'2026-10').remaining).toBe(8766);expect(calc(b,'2026-10').totalFundSpend).toBe(900);expect(calc(b,'2026-10').ledgerCheck).toBe(0);});
 it('renames and deactivates without changing IDs, recorded amounts or totals; reactivation preserves them',()=>{let b=changeCategory(blankBook(),'2026-10','future',custom('fixed'));b.months['2026-10'].plan['custom-test']=4500;b.months['2026-11'].actual['custom-test']=1234;const before=calc(b,'2026-10');b=changeCategory(b,'2026-10','future',{...custom('fixed'),name:'Annual service',archived:true});expect(calc(b,'2026-10')).toEqual(before);expect(b.months['2026-11'].actual['custom-test']).toBe(1234);expect(b.months['2026-12'].categories?.find(c=>c.id==='custom-test')?.archived).toBe(true);b=changeCategory(b,'2026-10','month',{...custom('fixed'),name:'Annual service'});expect(b.months['2026-11'].categories?.find(c=>c.id==='custom-test')?.archived).toBe(true);});
 it('adds manual income and expenses to their matching totals',()=>{let b=changeCategory(blankBook(),'2026-10','month',custom('income'));b.months['2026-10'].plan['custom-test']=10000;b.months['2026-10'].actual['custom-test']=9000;expect(calc(b,'2026-10').income).toBe(9000);expect(calc(b,'2026-10').incomePlan).toBe(10000);expect(groupTotal(b.months['2026-10'],'income','actual')).toBe(9000);});
 it('confirms Plan only on manual categories and closed months reject it',()=>{const b=blankBook();b.months['2026-10'].plan.internet=3456;expect(confirmPlan(b,'2026-10','internet').months['2026-10'].actual.internet).toBe(3456);expect(()=>confirmPlan(b,'2026-10','groceries')).toThrow();expect(()=>confirmPlan(b,'2026-10','unknown')).toThrow();b.months['2026-10'].closed=true;expect(()=>confirmPlan(b,'2026-10','internet')).toThrow('closed');});
 it('protects core identities, rejects duplicate names and invalid groups',()=>{const b=blankBook(),core=b.months['2026-10'].categories!.find(c=>c.id==='mv')!;expect(()=>changeCategory(b,'2026-10','month',{...core,archived:true})).toThrow('coreCategory');expect(()=>changeCategory(b,'2026-10','month',{...custom(),name:'Groceries'})).toThrow('categoryName');expect(()=>changeCategory(b,'2026-10','month',{...custom(),group:'constructor' as any})).toThrow('categories');});
 it('keeps closed month definitions and snapshot names during subsequent changes',()=>{let b=changeCategory(blankBook(),'2026-10','future',custom());const m=b.months['2026-10'];m.checks={income:true,fixed:true,ledger:true,assets:true};m.assets={dca:0,mm:0};b=closeMonth(b,'2026-10');const snap=structuredClone(b.history);b=changeCategory(b,'2026-11','future',{...custom(),name:'New name'});expect(b.history).toEqual(snap);expect(b.months['2026-10'].categories?.find(c=>c.id==='custom-test')?.name).toBe('Coffee & Tea');});
 it('imports legacy CSV and roundtrips catalog, folded state and archived categories without loss',()=>{let b=importCSV(csv(legacy()));b=changeCategory(b,'2026-10','future',{...custom(),name:'Tea, "咖啡"',archived:true});b.months['2026-10'].expanded!.income=false;const text=csv(b);expect(csv(importCSV(text))).toBe(text);});
 it('formats percentages with zero denominators and refunds; allocation remains exact and negative General only',()=>{expect(percentage(1,0)).toBe('—');expect(percentage(-50,1000)).toBe('-5.0%');expect(percentage(801,1000)).toBe('80.1%');expect(Object.values(allocate(80101,{General:70,Travel:30,Pet:0,Irregular:0})).reduce((a,b)=>a+b)).toBe(80101);expect(allocate(-100,{General:70,Travel:30,Pet:0,Irregular:0})).toEqual({General:-100,Travel:0,Pet:0,Irregular:0});});
 it('rejects schema 3 with missing metadata rather than silently rebuilding it',()=>{const b=blankBook();delete b.months['2026-10'].categories;expect(()=>migrateBook(b)).toThrow('invalidBook');});
});
