export const MONTHS=['2026-10','2026-11','2026-12'] as const;
export type MonthId=typeof MONTHS[number];
export const FUNDS=['General','Travel','Pet','Irregular'] as const;
export type Fund=typeof FUNDS[number];
export const CATEGORIES=['Groceries','Charging/407','Entertainment','Misc','Funded'] as const;
export type Category=typeof CATEGORIES[number];
export const GROUPS={income:['pw','mv','leo'],personal:['pwPersonal','mvPersonal','investment'],fixed:['insurance','condo','tax','internet','mortgage','car','ikea'],daily:['groceries','charging','entertainment','misc','streaming']} as const;
export const LABELS:Record<string,string>={pw:'PW Salary',mv:'MV Income',leo:'Leo Repayment',pwPersonal:'PW Personal',mvPersonal:'MV Personal',investment:'Investment',insurance:'Insurance',condo:'Condo Admin',tax:'Property Tax',internet:'Internet',mortgage:'Mortgage',car:'Car Payment',ikea:'Ikea Payment',groceries:'Groceries',charging:'Charging/407',entertainment:'Entertainment',misc:'Misc',streaming:'Streaming'};
export const KEYS=Object.values(GROUPS).flat() as string[];
export const DAILY:Record<string,Category>={groceries:'Groceries',charging:'Charging/407',entertainment:'Entertainment',misc:'Misc'};
export type Transaction={id:string,date:string,item:string,category:Category,amount:number,fund:Fund|''};
export type Month={plan:Record<string,number>,actual:Record<string,number|null>,shares:Record<Fund,number>,transactions:Transaction[],checks:Record<'income'|'fixed'|'ledger'|'assets',boolean>,assets:{dca:number|null,mm:number|null},closed:boolean,revision:number,closedAt:string|null,exportedRevision:number|null,archivedRevision:number|null,needsArchive:boolean,exportedAt?:string|null,archivedAt?:string|null};
export type Book={schema:1,currency:'CAD',id:string,opening:{funds:Record<Fund,number>,savings:number,receivables:number,dca:number,mm:number},rules:{mvBaseline:number},months:Record<MonthId,Month>,history:{month:MonthId,revision:number,closedAt:string,snapshot:Month}[],settings:{theme:'system'|'light'|'dark',glass:number,reduceMotion:boolean,reduceTransparency:boolean},lastBackup:string|null};
export const cents=(n:number)=>Math.round((n+Number.EPSILON)*100);
export const dollars=(n:number)=>n/100;
export const money=(n:number)=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(n/100);
export const shortMonth=(m:MonthId)=>({ '2026-10':'October','2026-11':'November','2026-12':'December'}[m]);
export const monthLabel=(m:MonthId)=>`${Number(m.slice(5))}月`;
export function blankBook():Book {const months={} as Book['months'];for(const m of MONTHS)months[m]={plan:Object.fromEntries(KEYS.map(k=>[k,0])),actual:Object.fromEntries(KEYS.filter(k=>!DAILY[k]).map(k=>[k,null])),shares:{General:70,Travel:30,Pet:0,Irregular:0},transactions:[],checks:{income:false,fixed:false,ledger:false,assets:false},assets:{dca:null,mm:null},closed:false,revision:1,closedAt:null,exportedRevision:null,archivedRevision:null,needsArchive:false};return {schema:1,currency:'CAD',id:crypto.randomUUID(),opening:{funds:{General:0,Travel:0,Pet:0,Irregular:0},savings:0,receivables:0,dca:0,mm:0},rules:{mvBaseline:200000},months,history:[],settings:{theme:'system',glass:65,reduceMotion:false,reduceTransparency:false},lastBackup:null};}
const sum=(xs:number[])=>xs.reduce((a,b)=>a+b,0);
export function actual(m:Month,k:string):number {return DAILY[k]?sum(m.transactions.filter(t=>t.category===DAILY[k]&&!t.fund).map(t=>t.amount)):m.actual[k]??m.plan[k];}
export function calc(book:Book,id:MonthId){const m=book.months[id];const total=(keys:readonly string[],mode:'plan'|'actual')=>sum(keys.map(k=>mode==='plan'?m.plan[k]:actual(m,k)));const savingPlan=Math.max(0,m.plan.mv-book.rules.mvBaseline),savings=Math.max(0,actual(m,'mv')-book.rules.mvBaseline);const incomePlan=total(GROUPS.income,'plan'),income=total(GROUPS.income,'actual');const expensesPlan=total([...GROUPS.personal,...GROUPS.fixed,...GROUPS.daily],'plan'),expenses=total([...GROUPS.personal,...GROUPS.fixed,...GROUPS.daily],'actual');const surplusPlan=incomePlan-expensesPlan-savingPlan,surplus=income-expenses-savings;const spent=Object.fromEntries(FUNDS.map(f=>[f,sum(m.transactions.filter(t=>t.fund===f).map(t=>t.amount))])) as Record<Fund,number>;return {incomePlan,income,savingPlan,savings,surplusPlan,surplus,spent,totalFundSpend:sum(Object.values(spent)),remaining:total(GROUPS.daily,'plan')-total(GROUPS.daily,'actual'),household:actual(m,'mv')-actual(m,'mvPersonal')-savings,cash:surplus-sum(Object.values(spent)),ledgerCheck:sum(m.transactions.map(t=>t.amount))-sum(Object.keys(DAILY).map(k=>actual(m,k)))-sum(Object.values(spent))};}
export function allocate(amount:number,shares:Record<Fund,number>){if(!shares||FUNDS.some(f=>!Number.isFinite(shares[f])||shares[f]<0)||Math.abs(FUNDS.reduce((n,f)=>n+shares[f],0)-100)>0.000001)throw new Error('Fund 分配比例合计必须为 100%。');const a={General:0,Travel:0,Pet:0,Irregular:0};if(amount<=0){a.General=amount;return a;}for(const f of FUNDS)a[f]=Math.floor(amount*shares[f]/100);let left=amount-FUNDS.reduce((n,f)=>n+a[f],0);const order=FUNDS.map((f,i)=>({f,i,remainder:amount*shares[f]/100-a[f]})).sort((x,y)=>y.remainder-x.remainder||x.i-y.i);for(let i=0;i<left;i++)a[order[i%4].f]++;return a;}
export function position(book:Book,id:MonthId){let funds={...book.opening.funds},savings=book.opening.savings,receivables=book.opening.receivables;for(const mi of MONTHS){const m=book.months[mi],c=calc(book,mi),opening={...funds},savingsOpening=savings,receivablesOpening=receivables;const allocation=allocate(m.closed?c.surplus:0,m.shares),planned=allocate(c.surplusPlan,m.shares);for(const f of FUNDS)funds[f]+=allocation[f]-c.spent[f];if(m.closed){savings+=c.savings;receivables-=actual(m,'leo');}if(mi===id)return {opening,closing:{...funds},allocation,planned,savingsOpening,savings,receivablesOpening,receivables};}throw new Error('月份不在试运行范围内');}
export function validateTransaction(t:Transaction,month:MonthId){if(typeof t.id!=='string'||!t.id||typeof t.item!=='string'||!t.item.trim()||t.item.length>200)throw new Error('请填写不超过 200 字的项目。');if(!/^2026-(10|11|12)-\d{2}$/.test(t.date)||t.date.slice(0,7)!==month||new Date(t.date+'T12:00:00Z').toISOString().slice(0,10)!==t.date)throw new Error('日期必须属于当前月份。');if(!Number.isSafeInteger(t.amount)||t.amount===0||Math.abs(t.amount)>1e12)throw new Error('请输入有效金额，退款使用负数。');if(!CATEGORIES.includes(t.category)||t.fund!==''&&!FUNDS.includes(t.fund))throw new Error('类别或资金来源无效。');if(t.category==='Funded'&&!t.fund)throw new Error('Funded 支出需要选择 Fund。');}
export function validateBook(v:unknown):Book {const b=v as Book;if(!b||b.schema!==1||b.currency!=='CAD'||typeof b.id!=='string'||!b.settings||!Array.isArray(b.history))throw new Error('不是兼容的 VEWU 备份。');const cash=(x:unknown)=>typeof x==='number'&&Number.isSafeInteger(x)&&Math.abs(x)<=1e12;if(!b.opening||!b.opening.funds||![...FUNDS.map(f=>b.opening.funds[f]),b.opening.savings,b.opening.receivables,b.opening.dca,b.opening.mm,b.rules?.mvBaseline].every(cash))throw new Error('期初金额无效。');const ids=new Set<string>();let priorClosed=true;for(const id of MONTHS){const m=b.months?.[id];if(!m||!KEYS.every(k=>cash(m.plan?.[k]))||!m.actual||!m.checks||!m.assets||!Array.isArray(m.transactions)||typeof m.closed!=='boolean'||!Number.isSafeInteger(m.revision)||m.revision<1)throw new Error('月份数据不完整。');for(const k of KEYS.filter(k=>!DAILY[k]))if(m.actual[k]!==null&&!cash(m.actual[k]))throw new Error('实际金额无效。');if(![m.assets.dca,m.assets.mm].every(x=>x===null||cash(x)))throw new Error('投资余额无效。');for(const k of ['income','fixed','ledger','assets'])if(typeof m.checks[k as keyof Month['checks']]!=='boolean')throw new Error('核对状态无效。');allocate(0,m.shares);if(m.closed&&(!Object.values(m.checks).every(Boolean)||m.assets.dca===null||m.assets.mm===null||!m.closedAt))throw new Error('已月结月份缺少核对记录。');if(m.closed&&!priorClosed)throw new Error('月结顺序不连续。');priorClosed=m.closed;for(const t of m.transactions){validateTransaction(t,id);if(ids.has(t.id))throw new Error('交易标识重复。');ids.add(t.id);}}if(!['system','light','dark'].includes(b.settings.theme)||!Number.isFinite(b.settings.glass)||b.settings.glass<0||b.settings.glass>100)throw new Error('外观设置无效。');for(const h of b.history)if(!MONTHS.includes(h.month)||!Number.isSafeInteger(h.revision)||typeof h.closedAt!=='string'||!h.snapshot?.plan)throw new Error('历史版本无效。');return structuredClone(b);}
export function editMonth(book:Book,id:MonthId,change:(m:Month)=>void):Book{if(book.months[id].closed)throw new Error('请先重新打开此月份。');const b=structuredClone(book),m=b.months[id];change(m);m.revision++;m.exportedRevision=null;m.archivedRevision=null;m.exportedAt=null;m.archivedAt=null;m.checks={income:false,fixed:false,ledger:false,assets:false};validateBook(b);return b;}
export function closeMonth(book:Book,id:MonthId){const b=structuredClone(book),m=b.months[id],idx=MONTHS.indexOf(id);if(m.closed)throw new Error('该月份已月结。');if(idx>0&&!b.months[MONTHS[idx-1]].closed)throw new Error('请先完成上一个月的月结。');if(!Object.values(m.checks).every(Boolean)||m.assets.dca===null||m.assets.mm===null)throw new Error('请完成四项核对，并填写月末投资余额。');if(calc(b,id).ledgerCheck!==0)throw new Error('流水对账未通过。');m.closed=true;m.closedAt=new Date().toISOString();m.needsArchive=true;b.history.push({month:id,revision:m.revision,closedAt:m.closedAt,snapshot:structuredClone(m)});return b;}
export function reopenMonth(book:Book,id:MonthId){const b=structuredClone(book);for(const mId of MONTHS.slice(MONTHS.indexOf(id))){const m=b.months[mId];if(m.closed||m.exportedRevision!==null||m.archivedRevision!==null)m.needsArchive=true;m.closed=false;m.closedAt=null;m.exportedRevision=null;m.archivedRevision=null;m.exportedAt=null;m.archivedAt=null;m.revision++;m.checks={income:false,fixed:false,ledger:false,assets:false};}return b;}
export function todayIn(month:MonthId){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const p=(t:string)=>parts.find(x=>x.type===t)?.value;const date=`${p('year')}-${p('month')}-${p('day')}`;return date.startsWith(month)?date:`${month}-01`;}
