import {describe,it,expect} from 'vitest';
import {blankBook,createBook,calc,allocate,position,closeMonth,reopenMonth,editMonth,applyScoped,validateBook,validateTransaction,migrateV1,MONTHS,GROUPS,backupStale,reminder,money,parseAmount,investmentPosition,type Book,type MonthId} from './model';
import {csv,importCSV,prepareBackup} from './export';
const ready=(b:Book,id:MonthId)=>{b.months[id].checks={income:true,fixed:true,ledger:true,assets:true};b.months[id].assets={dca:100,mm:200};return b;};
const tx={id:'a',date:'2026-10-01',item:'x',category:'Misc' as const,amount:12345,fund:'' as const};
describe('household ledger',()=>{
 it('initializes the pilot rules consistently for all three new months without private income or transactions',()=>{const b=createBook();for(const id of MONTHS){expect(b.months[id].plan).toEqual(b.months['2026-10'].plan);expect(b.months[id].plan.mv).toBe(200000);expect(b.months[id].plan.pwPersonal).toBe(100000);expect(b.months[id].plan.mvPersonal).toBe(100000);expect(b.months[id].plan.investment).toBe(14083);expect(b.months[id].actual.mv).toBeNull();expect(b.months[id].plan.pw).toBe(0);expect(b.months[id].transactions).toEqual([]);}});

 it('keeps Plan Surplus at 801.24 while early actual spending is incomplete',()=>{const b=blankBook(),m=b.months['2026-10'];Object.assign(m.plan,{pw:200000,mv:200000,pwPersonal:100000,mvPersonal:100000,investment:14083,streaming:2486,groceries:50000,insurance:53307});m.transactions=[tx];expect(calc(b,'2026-10').surplusPlan).toBe(80124);expect(calc(b,'2026-10').surplus).not.toBe(80124);expect(money(80124)).toBe('$801');});
 it('sweeps MV excess independently without changing ordinary surplus',()=>{const b=blankBook(),m=b.months['2026-10'];m.plan.mv=200000;m.plan.mvPersonal=100000;const before=calc(b,'2026-10');m.actual.mv=265000;const after=calc(b,'2026-10');expect(after.savings).toBe(65000);expect(after.surplus).toBe(before.surplus);expect(after.household).toBe(100000);});
 it('classifies Streaming as Fixed and counts it exactly once',()=>{const b=blankBook();b.months['2026-10'].plan.streaming=2486;expect(GROUPS.fixed).toContain('streaming');expect(GROUPS.daily).not.toContain('streaming');expect(calc(b,'2026-10').remaining).toBe(0);expect(calc(b,'2026-10').surplusPlan).toBe(-2486);expect(calc(b,'2026-10').surplus).toBe(-2486);});
 it('counts fund spending once and refunds reverse the same source',()=>{const b=blankBook();b.months['2026-10'].transactions=[{...tx,id:'a',amount:12345,fund:'Travel'},{...tx,id:'b',amount:-2345,fund:'Travel'},{...tx,id:'c',amount:4000}];const c=calc(b,'2026-10');expect(c.surplus).toBe(-4000);expect(c.totalFundSpend).toBe(10000);expect(c.cash).toBe(-14000);expect(c.ledgerCheck).toBe(0);expect(position(b,'2026-10').closing.Travel).toBe(-10000);});
 it('allocates exact cents with every deficit assigned to General',()=>{expect(allocate(-501,{General:70,Travel:30,Pet:0,Irregular:0})).toEqual({General:-501,Travel:0,Pet:0,Irregular:0});for(let n=0;n<1000;n++){const a=allocate(n,{General:0,Travel:33.4,Pet:33.3,Irregular:33.3});expect(Object.values(a).reduce((x,y)=>x+y,0)).toBe(n);expect(Math.min(...Object.values(a))).toBeGreaterThanOrEqual(0);}});
 it('rolls three months forward and retains old versions after correction',()=>{let b=blankBook();b.opening.funds.General=-500;for(const id of MONTHS){b.months[id].plan.pw=10000;b=closeMonth(ready(b,id),id);}expect(position(b,'2026-12').closing.General).toBe(20500);expect(position(b,'2026-12').closing.Travel).toBe(9000);const h=structuredClone(b.history);b=reopenMonth(b,'2026-10');b=editMonth(b,'2026-10',m=>{m.actual.pw=20000;});for(const id of MONTHS)b=closeMonth(ready(b,id),id);expect(position(b,'2026-12').closing.General).toBe(27500);expect(b.history.slice(0,3)).toEqual(h);expect(b.history).toHaveLength(6);});
 it('requires sequential closing and complete checks',()=>{const b=blankBook();expect(()=>closeMonth(b,'2026-10')).toThrow('checks');expect(()=>closeMonth(ready(b,'2026-11'),'2026-11')).toThrow('sequence');});
 it('applies plans and shares only to the requested open months, preserving actuals and transactions',()=>{const b=blankBook();b.months['2026-11'].actual.mv=265000;b.months['2026-11'].transactions=[{...tx,id:'nov',date:'2026-11-03'}];const one=applyScoped(b,'2026-10','month',m=>{m.plan.groceries=10000;});expect(one.months['2026-11'].plan.groceries).toBe(0);const all=applyScoped(b,'2026-10','future',m=>{m.plan.groceries=10000;m.shares={General:60,Travel:30,Pet:10,Irregular:0};});expect(all.months['2026-12'].plan.groceries).toBe(10000);expect(all.months['2026-11'].actual).toEqual(b.months['2026-11'].actual);expect(all.months['2026-11'].transactions).toEqual(b.months['2026-11'].transactions);expect(all.months['2026-12'].shares.Pet).toBe(10);expect(b.months['2026-10'].plan.groceries).toBe(0);});
 it('does not overwrite closed months during scoped edits',()=>{let b=blankBook();for(const id of MONTHS)b=closeMonth(ready(b,id),id);expect(()=>applyScoped(b,'2026-10','future',m=>{m.plan.pw=1;})).toThrow('closed');});
 it('rejects invalid dates, duplicate IDs, fractional cents and invalid shares',()=>{const b=blankBook();expect(()=>validateTransaction({...tx,date:'2026-11-31'},'2026-11')).toThrow();b.months['2026-10'].transactions=[tx,tx];expect(()=>validateBook(b)).toThrow('duplicate');b.months['2026-10'].transactions=[];b.months['2026-10'].plan.pw=1.1;expect(()=>validateBook(b)).toThrow();expect(()=>allocate(100,{General:90,Travel:30,Pet:0,Irregular:0})).toThrow('shares');expect(parseAmount('1.23')).toBe(123);expect(parseAmount('',true)).toBeNull();expect(parseAmount('1.234')).toBe(123);});
});
describe('V1 migration and full CSV',()=>{
 it('carries only confirmed investment balances, preserving unknown closing values',()=>{let b=blankBook();b.opening.dca=12345;b.opening.mm=67890;expect(investmentPosition(b,'2026-10')).toEqual({dca:12345,mm:67890});b.months['2026-10'].assets={dca:999,mm:888};expect(investmentPosition(b,'2026-11')).toEqual({dca:12345,mm:67890});b=closeMonth(ready(b,'2026-10'),'2026-10');expect(investmentPosition(b,'2026-11')).toEqual({dca:100,mm:200});expect(b.months['2026-11'].assets).toEqual({dca:null,mm:null});});

 it('preserves all V1 financial fields, IDs, nulls, settings and histories without inserting defaults',()=>{const old=blankBook();old.schema=1;delete old.settings.language;delete old.dataRevision;delete old.backedUpRevision;delete old.reminderDismissedOn;old.settings.theme='dark';old.months['2026-10'].transactions=[tx];old.months['2026-11'].plan.streaming=1234;old.months['2026-12'].actual.pw=0;const original=structuredClone(old);const next=migrateV1(old);expect(next.schema).toBe(2);expect(next.months).toEqual(old.months);expect(next.opening).toEqual(old.opening);expect(next.history).toEqual(old.history);expect(next.settings.theme).toBe('dark');expect(old).toEqual(original);expect(migrateV1(next)).toEqual(next);});
 it('round-trips exact cents, null vs zero, special characters, arrays, settings and history byte for byte',()=>{let b=blankBook();b.months['2026-10'].transactions=[{...tx,item:'=SUM(1,2)\n"商店", café 🌕',fund:'Pet'}];b.months['2026-11'].actual.pw=0;b=closeMonth(ready(b,'2026-10'),'2026-10');b.settings.language='en';const out=csv(b),back=importCSV(out);expect(back).toEqual(b);expect(csv(back)).toBe(out);expect(back.months['2026-11'].actual.mv).toBeNull();expect(out).toContain('escaped text');expect(out).toContain("'=SUM(1,2)");});
 it('replaces rather than appends on repeated imports',()=>{const b=blankBook();b.months['2026-10'].transactions=[tx];const out=csv(b);const one=importCSV(out),two=importCSV(out);expect(two).toEqual(one);expect(two.months['2026-10'].transactions).toHaveLength(1);});
 it('rejects malformed, truncated, duplicate, unsupported and unsafe rows before replacement',()=>{const out=csv(blankBook());expect(()=>importCSV(out.replace('VEWU Finance CSV','old CSV'))).toThrow('csvVersion');expect(()=>importCSV('"unfinished')).toThrow('csv');expect(()=>importCSV(out+'"DATA","2","/schema","number","2"\r\n')).toThrow('csv');expect(()=>importCSV(out+'"DATA","2","/__proto__","object",""\r\n')).toThrow('csv');expect(()=>importCSV(out.slice(0,out.indexOf('"/months')))).toThrow();});
 it('stamps only generated backups, keeps exact state, and flags new edits',()=>{const b=blankBook(),now=new Date('2026-10-04T12:00:00Z');const prepared=prepareBackup(b,now);expect(b.lastBackup).toBeNull();expect(prepared.book.lastBackup).toBe(now.toISOString());expect(importCSV(prepared.text)).toEqual(prepared.book);expect(backupStale(prepared.book,new Date('2026-10-11T12:00:00Z'))).toBe(false);expect(backupStale(prepared.book,new Date('2026-10-11T12:00:01Z'))).toBe(true);const changed=editMonth(prepared.book,'2026-10',m=>{m.actual.pw=123;});expect(changed.backedUpRevision).not.toBe(changed.dataRevision);expect(changed.months['2026-10'].exportedRevision).toBeNull();});
 it('reminds on local days 1–7, respects daily dismissal, and handles December in January',()=>{let b=blankBook();const nov=new Date('2026-11-02T12:00:00Z');expect(reminder(b,nov)).toEqual({month:'2026-10',reason:'close'});b.reminderDismissedOn='2026-11-02';expect(reminder(b,nov)).toBeNull();expect(reminder(b,new Date('2026-11-03T12:00:00Z'))?.reason).toBe('close');b.reminderDismissedOn=null;b=closeMonth(ready(b,'2026-10'),'2026-10');expect(reminder(b,nov)?.reason).toBe('backup');b=prepareBackup(b,nov).book;expect(reminder(b,nov)).toBeNull();expect(reminder(b,new Date('2026-11-08T12:00:00Z'))).toBeNull();expect(reminder(b,new Date('2027-01-07T12:00:00Z'))).toEqual({month:'2026-12',reason:'close'});expect(reminder(b,new Date('2026-10-04T12:00:00Z'))).toBeNull();});
});
