import {describe,it,expect} from 'vitest';
import {blankBook,calc,allocate,position,closeMonth,reopenMonth,editMonth,validateBook,validateTransaction,MONTHS,type Book,type MonthId} from './model';
import {snapshotRows,csv,archive} from './export';
const ready=(b:Book,id:MonthId)=>{b.months[id].checks={income:true,fixed:true,ledger:true,assets:true};b.months[id].assets={dca:100,mm:200};return b;};
describe('household ledger',()=>{
 it('sweeps all excess MV income without enlarging lifestyle funds',()=>{const b=blankBook(),m=b.months['2026-10'];m.plan.mv=200000;m.plan.mvPersonal=100000;const before=calc(b,'2026-10');m.actual.mv=265000;const after=calc(b,'2026-10');expect(after.savings).toBe(65000);expect(after.surplus).toBe(before.surplus);expect(after.household).toBe(100000);});
 it('counts funded spending once, with refunds reversing the original source',()=>{const b=blankBook(),m=b.months['2026-10'];m.transactions=[{id:'a',date:'2026-10-01',item:'a',category:'Groceries',amount:12345,fund:'Travel'},{id:'b',date:'2026-10-02',item:'refund',category:'Groceries',amount:-2345,fund:'Travel'},{id:'c',date:'2026-10-02',item:'food',category:'Groceries',amount:4000,fund:''}];const c=calc(b,'2026-10');expect(c.surplus).toBe(-4000);expect(c.totalFundSpend).toBe(10000);expect(c.cash).toBe(-14000);expect(c.ledgerCheck).toBe(0);expect(position(b,'2026-10').closing.Travel).toBe(-10000);});
 it('allocates positive surplus exactly to cents and deficits only to General',()=>{expect(allocate(-501,{General:70,Travel:30,Pet:0,Irregular:0})).toEqual({General:-501,Travel:0,Pet:0,Irregular:0});for(let n=0;n<1000;n++){const a=allocate(n,{General:0,Travel:33.4,Pet:33.3,Irregular:33.3});expect(Object.values(a).reduce((x,y)=>x+y,0)).toBe(n);expect(Math.min(...Object.values(a))).toBeGreaterThanOrEqual(0);}});
 it('requires sequential closing and complete checks',()=>{const b=blankBook();expect(()=>closeMonth(b,'2026-10')).toThrow();expect(()=>closeMonth(ready(b,'2026-11'),'2026-11')).toThrow('上一个月');});
 it('rolls three months forward and invalidates later closes after correction',()=>{let b=blankBook();b.opening.funds.General=-500;for(const id of MONTHS){b.months[id].plan.pw=10000;b=closeMonth(ready(b,id),id);}expect(position(b,'2026-12').closing.General).toBe(20500);expect(position(b,'2026-12').closing.Travel).toBe(9000);const history=b.history.length;b=reopenMonth(b,'2026-10');b=editMonth(b,'2026-10',m=>{m.actual.pw=20000;});for(const id of MONTHS)b=closeMonth(ready(b,id),id);expect(position(b,'2026-12').closing.General).toBe(27500);expect(b.history).toHaveLength(history+3);});
 it('rejects invalid dates, duplicate transactions, noninteger money and invalid shares',()=>{const b=blankBook(),t={id:'a',date:'2026-11-31',item:'x',category:'Misc' as const,amount:1,fund:'' as const};expect(()=>validateTransaction(t,'2026-11')).toThrow();t.date='2026-10-01';b.months['2026-10'].transactions=[t,t];expect(()=>validateBook(b)).toThrow('重复');b.months['2026-10'].transactions=[];b.months['2026-10'].plan.pw=1.1;expect(()=>validateBook(b)).toThrow();expect(()=>allocate(100,{General:90,Travel:30,Pet:0,Irregular:0})).toThrow();});
 it('restoring the same snapshot replaces the book without appending transactions',()=>{const b=blankBook();b.months['2026-10'].transactions=[{id:'one',date:'2026-10-01',item:'test',category:'Misc',amount:100,fund:''}];const first=validateBook(JSON.parse(JSON.stringify(b))),second=validateBook(JSON.parse(JSON.stringify(first)));expect(second.months['2026-10'].transactions).toHaveLength(1);expect(snapshotRows(second)).toEqual(snapshotRows(first));});
 it('prevents spreadsheet formula injection in transaction strings',()=>{const b=blankBook();b.months['2026-10'].transactions=[{id:'one',date:'2026-10-01',item:'=1+1',category:'Misc',amount:100,fund:''}];expect(csv(b)).toContain('"\'=1+1"');});
 it('exports a readable workbook, full snapshot and restorable backup',async()=>{const b=closeMonth(ready(blankBook(),'2026-10'),'2026-10');const blob=await archive(b,'2026-10');const {default:JSZip}=await import('jszip');const zip=await JSZip.loadAsync(await blob.arrayBuffer());expect(Object.keys(zip.files)).toContain('2026-10-report.xlsx');expect(validateBook(JSON.parse(await zip.file('VEWU-backup.json')!.async('string')))).toEqual(b);const {default:ExcelJS}=await import('exceljs');const wb=new ExcelJS.Workbook();await wb.xlsx.load(await zip.file('2026-10-report.xlsx')!.async('arraybuffer'));expect(wb.worksheets).toHaveLength(2);expect(wb.worksheets[0].getCell('B1').value).toContain('2026-10');});
});
