import {beforeEach,describe,it,expect,vi} from 'vitest';
import {IDBFactory,IDBObjectStore} from 'fake-indexeddb';
import {blankBook,closeMonth,type Book} from './model';
import {loadBook,saveBook,replaceBook} from './storage';
beforeEach(()=>{vi.stubGlobal('indexedDB',new IDBFactory());});
async function raw(write?:unknown,key='current') {const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('vewu-finance',1);r.onupgradeneeded=()=>r.result.createObjectStore('book');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});return new Promise<unknown>((resolve,reject)=>{const tx=db.transaction('book',write===undefined?'readonly':'readwrite'),store=tx.objectStore('book');let result:unknown;if(write!==undefined)store.put(write,key);const r=store.get(key);r.onsuccess=()=>{result=r.result;};tx.oncomplete=()=>{db.close();resolve(result);};tx.onabort=()=>{db.close();reject(tx.error);};});}
const v1=():Book=>{const b=blankBook();b.schema=1;delete b.settings.language;delete b.dataRevision;delete b.backedUpRevision;delete b.reminderDismissedOn;b.months['2026-10'].plan.pw=123456;b.months['2026-10'].checks={income:true,fixed:true,ledger:true,assets:true};b.months['2026-10'].assets={dca:0,mm:0};const closed=closeMonth(b,'2026-10');closed.schema=1;delete closed.dataRevision;return closed;};
describe('atomic storage upgrade',()=>{
 it('returns null only for an absent ledger',async()=>{expect(await loadBook()).toBeNull();});
 it('saves the complete V1 snapshot and migrates the unchanged current record atomically',async()=>{const old=v1();await raw(old);const next=await loadBook();expect(next?.schema).toBe(2);expect(next?.months).toEqual(old.months);expect(next?.history).toEqual(old.history);expect(await raw(undefined,`v1-before-v2:${old.id}`)).toEqual(old);expect(await raw()).toEqual(next);expect(await loadBook()).toEqual(next);});
 it('keeps invalid V1 intact and throws instead of creating an empty ledger',async()=>{const old=v1();old.months['2026-10'].plan.pw=1.25;await raw(old);await expect(loadBook()).rejects.toThrow();expect(await raw()).toEqual(old);});
 it('rolls back the V1 snapshot and current write if a migration write fails',async()=>{const old=v1();await raw(old);const original=IDBObjectStore.prototype.put;const spy=vi.spyOn(IDBObjectStore.prototype,'put').mockImplementation(function(this:IDBObjectStore,value:unknown,key?:IDBValidKey){if(key==='current'){this.transaction.abort();throw new DOMException('Quota','QuotaExceededError');}return original.call(this,value,key);});await expect(loadBook()).rejects.toThrow();spy.mockRestore();expect(await raw()).toEqual(old);expect(await raw(undefined,`v1-before-v2:${old.id}`)).toBeUndefined();});
 it('rejects invalid replacement without altering the current record and retains a pre-import snapshot',async()=>{const b=blankBook();await saveBook(b);const invalid=structuredClone(b);invalid.opening.savings=NaN;await expect(replaceBook(invalid)).rejects.toThrow();expect(await raw()).toEqual(b);const incoming=blankBook();await replaceBook(incoming);expect(await raw()).toEqual(incoming);expect(await raw(undefined,'before-csv-import')).toEqual(b);});
 it('rolls back CSV replacement and its snapshot on a transaction failure',async()=>{const b=blankBook();await saveBook(b);const original=IDBObjectStore.prototype.put;const spy=vi.spyOn(IDBObjectStore.prototype,'put').mockImplementation(function(this:IDBObjectStore,value:unknown,key?:IDBValidKey){if(key==='current'){this.transaction.abort();throw new DOMException('Quota','QuotaExceededError');}return original.call(this,value,key);});await expect(replaceBook(blankBook())).rejects.toThrow();spy.mockRestore();expect(await raw()).toEqual(b);expect(await raw(undefined,'before-csv-import')).toBeUndefined();});
});
